#!/bin/bash

# Postavimo URL za datoteko z imeni predmetov na GitHubu
URL="https://raw.githubusercontent.com/jsvnk/OIKT/main/mape?token=GHSAT0AAAAAACJ6JN5LR4276KIRXVHDLZ4QZKJF6LQ"

# Ime krovne mape
root_folder="studij"

# Preverimo, ali krovna mapa obstaja in jo izbrišemo, če obstaja
if [ -d "$root_folder" ]; then
  rm -r "$root_folder"
fi

# Ustvarimo krovno mapo
mkdir "$root_folder"

# Preberemo imena predmetov iz datoteke na GitHubu
curl -s "$URL" | while read -r subject; do
  year="2023-24"  # Lahko spremenite na ustrezno leto
  subject_folder="$root_folder/$year/$subject"
  
  # Ustvarimo mapo za predmet
  mkdir -p "$subject_folder/vaje"
  mkdir -p "$subject_folder/predavanja"
done

# Izpišemo drevesno strukturo novo ustvarjenih map
tree "$root_folder"
